fix folder content

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -21,6 +21,7 @@ set +e
 # it wastes flash
 #
 set R /
+set AUTOCNF no
 set FCONFIG /fs/microsd/etc/config.txt
 set FEXTRAS /fs/microsd/etc/extras.txt
 set FRC /fs/microsd/etc/rc.txt
@@ -176,12 +177,13 @@ else
 	fi
 
 	#
-	# If the airframe has been previously reset SYS_AUTCONFIG will have been set to 1 and other params will be reset on the next boot.
+	# Set AUTOCNF flag to use it in AUTOSTART scripts.
 	#
 	if param greater SYS_AUTOCONFIG 0
 	then
-		# Reset params except Airframe, RC calibration, sensor calibration, flight modes, total flight time, and next flight UUID.
-		param reset_all SYS_AUTOSTART RC* CAL_* COM_FLTMODE* LND_FLIGHT* TC_* COM_FLIGHT*
+		# Wipe out params except RC*, flight modes, total flight time, calibration parameters, next flight UUID
+		param reset_all SYS_AUTO* RC* COM_FLTMODE* LND_FLIGHT* TC_* CAL_ACC* CAL_GYRO* COM_FLIGHT*
+		set AUTOCNF yes
 	fi
 
 	#
@@ -205,26 +207,6 @@ else
 		. $BOARD_RC_DEFAULTS
 	fi
 	unset BOARD_RC_DEFAULTS
-
-	#
-	# Set parameters and env variables for selected SYS_AUTOSTART.
-	#
-	set AUTOSTART_PATH etc/init.d/rc.autostart
-	if ! param compare SYS_AUTOSTART 0
-	then
-		if param greater SYS_AUTOSTART 1000000
-		then
-			# Use external startup file
-			if [ $SDCARD_AVAILABLE = yes ]
-			then
-				set AUTOSTART_PATH etc/init.d/rc.autostart_ext
-			else
-				echo "ERROR [init] SD card not mounted - trying to load airframe from ROMFS"
-			fi
-		fi
-		. ${R}$AUTOSTART_PATH
-	fi
-	unset AUTOSTART_PATH
 
 	#
 	# Start the tone_alarm driver.
@@ -264,12 +246,40 @@ else
 	rgbled_ncp5623c start -X -q
 
 	#
+	# Set parameters and env variables for selected AUTOSTART.
+	#
+	set AUTOSTART_PATH etc/init.d/rc.autostart
+	if ! param compare SYS_AUTOSTART 0
+	then
+		if param greater SYS_AUTOSTART 1000000
+		then
+			# Use external startup file
+			if [ $SDCARD_AVAILABLE = yes ]
+			then
+				set AUTOSTART_PATH etc/init.d/rc.autostart_ext
+			else
+				echo "ERROR [init] SD card not mounted - trying to load airframe from ROMFS"
+			fi
+		fi
+		. ${R}$AUTOSTART_PATH
+	fi
+	unset AUTOSTART_PATH
+
+	#
 	# Override parameters from user configuration file.
 	#
 	if [ -f $FCONFIG ]
 	then
 		echo "Custom: ${FCONFIG}"
 		. $FCONFIG
+	fi
+
+	#
+	# If autoconfig parameter was set, reset it and save parameters.
+	#
+	if [ $AUTOCNF = yes ]
+	then
+		param set SYS_AUTOCONFIG 0
 	fi
 
 	#
@@ -303,7 +313,7 @@ else
 	then
 		# Check for the mini using build with px4io fw file
 		# but not a px4IO
-		if ver hwtypecmp V5004000 V5006000
+		if ver hwtypecmp V540 V560
 		then
 			param set SYS_USE_IO 0
 		else
@@ -555,6 +565,7 @@ fi
 # Unset all script parameters to free RAM.
 #
 unset R
+unset AUTOCNF
 unset FCONFIG
 unset FEXTRAS
 unset FRC
